# Generated by Django 6.1 on 2026-09-28 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=150)),
                ('platform', models.CharField(max_length=100)),
                ('platform_file', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('portrait', models.CharField(max_length=255)),
                ('marquee', models.CharField(max_length=255)),
                ('video', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
