# Generated by Django 6.1 on 2026-09-28 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='technical_sheet',
            field=models.FileField(blank=True, upload_to='games/technical_sheets/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='marquee',
            field=models.ImageField(blank=True, upload_to='games/marquees/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='games/portraits/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, upload_to='games/videos/'),
        ),
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'user'), name='unique_game_rating_per_user')],
            },
        ),
    ]
