# Generated by Django 6.1 on 2026-09-28 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(blank=True, upload_to='platforms/')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform_file',
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.platform'),
        ),
    ]
