# Generated by Django 6.1 on 2026-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_platform_remove_game_platform_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cartridge',
            field=models.ImageField(blank=True, upload_to='games/cartridges/'),
        ),
    ]
