# Generated by Django 6.1 on 2026-09-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_cartridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
    ]
