# Generated by Django 6.1 on 2026-09-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_game_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='gamerating',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
