# Generated by Django 6.1 on 2026-09-30 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=150)),
                ('duration', models.PositiveIntegerField(help_text='Duración en minutos.')),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('studio', models.CharField(max_length=150)),
                ('portrait', models.ImageField(blank=True, upload_to='movies/portraits/')),
                ('landscape', models.ImageField(blank=True, upload_to='movies/landscapes/')),
                ('trailer', models.FileField(blank=True, upload_to='movies/trailers/')),
                ('description', models.TextField()),
                ('cast', models.TextField(blank=True, help_text='Actores principales separados por comas.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-year', 'title'),
            },
        ),
        migrations.CreateModel(
            name='MovieFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_movie_favorite')],
            },
        ),
        migrations.CreateModel(
            name='MovieWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_movie_watched')],
            },
        ),
    ]
